obj-$(CONFIG_BRICKED_HOTPLUG)	+= bricked_hotplug.o
obj-$(CONFIG_MSM_SLEEPER)	+= msm_sleeper.o
obj-$(CONFIG_INTELLI_PLUG)	+= intelli_plug.o
obj-$(CONFIG_CLUSTER_PLUG)	:= cluster_plug.o
obj-$(CONFIG_ASMP)		+= autosmp.o
